version: '3'
services:
    gm-redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'gm-redis:/data'
        networks:
            - gm-market
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    gm-postgres:
        image: postgis/postgis:16-3.4
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - '${POSTGRES_PORT:-5432}:5432'
        volumes:
          - gm-postgres:/var/lib/postgresql/data
        networks:
          - gm-market
        command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - gm-market
networks:
    gm-market:
        driver: bridge

volumes:
    gm-postgres:
        driver: local
    gm-redis:
        driver: local